### ISSUE TITLE
Do not export the Tracer type

### ISSUE THREAD

**Issue by achille-roussel** [stealthrocket/wasi-go#46]
`Tracer` is a wrapper for `System` which does not add any extra methods to the interface. However, we export the type so it is taking a lot of space on the documentation page:

![image](https://github.com/stealthrocket/wasi-go/assets/865510/b47eb206-6aad-4824-8bfa-abf826a76490)

I would like to recommend that we change the approach to unexport the `Tracer` type and instead use a function to construct the `System` decorator:

```go
func Trace(w io.Writer, s System) System {
    return &tracer{w, s}
}
```

One of the advantage of this approach is the Go documentation would show the `Trace` function as a subsection of `System`, which makes discovery a lot simpler. I believe it would also make it more explicit to the readers what the intent of this feature is, and remove a lot of distractions from the documentation space.

Let me know what you think!

**Comment by chriso** [comment]
Agreed!
