### ISSUE TITLE
Add SocketsExtension method by default in the System interface

### ISSUE THREAD

**Issue by achille-roussel** [stealthrocket/wasi-go#47]
The separation of `SocketsExtension` from `System` causes a lot of checks from compile time to run time. Creating wrappers of the `System` interface can easily _miss_ that they have to implement `SocketsExtension` if the underlying type does, resulting in unexpectedly disabling socket capabilities.

Since the implementation of the `System` and `SocketsExtension` interface is decoupled from the ABI, I would like to suggest that we merge the methods into `System` and remove the `SocketsExtension` interface.

For situations where a backend does not provide socket capabilities, I would suggest that we add a type which has the socket extension methods returning ENOSYS, that types can embed in order to easily declare that they don't support sockets. For example:

```go
type MySystemWithoutSockets struct {
    wasi.SocketsNotSupported
    ...
}
```

```go
package wasi

type SocketsNotSupported struct{}

func (SocketsNotSupported) SockOpen(ctx context.Context, family ProtocolFamily, socketType SocketType, protocol Protocol, rightsBase, rightsInheriting Rights) (FD, Errno) {
    return -1, ENOSYS
}

...
```

This is somewhat the inverse of the approach we have taken; instead of having extensions, implementations of `System` can declare the parts of the total interface that they don't support.

Let me know what you think!

**Comment by chriso** [comment]
Makes sense. It's been error prone having to check whether `System` implementations also implement `SocketsExtension`, and we don't have any use cases for `System` implementations that do not also implement `SocketsExtension`
