### ISSUE TITLE
nats

### ISSUE THREAD

**Issue by gedw99** [stealthrocket/wasi-go#57]
Maybe it would be cool to add NATS as it will allow it to run on windows also..

Ir maybe a generic MQ style api.

path_open_sockets.go might also work as nats supports standard tcp : https://docs.nats.io/reference/reference-protocols/nats-protocol#client-protocol

**Comment by achille-roussel** [comment]
Hello @gedw99, thanks for reaching out!

The more examples we have the better in my opinion, so definitely +1 on adding one with NATS.

Would you be able to submit a PR to contribute to the repository?

**Comment by gedw99** [comment]
Btw I assumed that the problem on windows is sockets, hence why I suggested nats.

maybe my assumptions are wrong ?

**Comment by achille-roussel** [comment]
I followed up on your question about Windows at https://github.com/stealthrocket/wasi-go/issues/79

NATS as a backend for networking is a very interesting avenue, it kind of reminds me of the nanomsg days of exposing high-level protocols behind low-level socket APIs. We don't see an immediate need for it in @stealthrocket at the moment, so it won't make sense for us to invest engineering time in it, but I'm happy to provide guidance if you end up submitting a contribution for it.

**Comment by gedw99** [comment]
@achille-roussel 

yeah I did not expect it to be that needed in the core.

i just started using DAPR and it’s pub sub system which has  a NATS Jetstream driver.

Wazero is also incorporated into DAPR http middleware. 

So I am going to try out that system .

will close this as I see that this feature does not belong here , but thanks for the explanation. You are very patient
