### ISSUE TITLE
Windows not supported ?

### ISSUE THREAD

**Issue by gedw99** [stealthrocket/wasi-go#79]
I saw in the readme that Windows does not work , or is supported.

i guess it’s because of sockets ? 

I ask because for my use case Windows would make it alot easier for those devs using it.

prefer not to have to use docker , before you suggest that , or WSL

**Comment by gedw99** [comment]
Just brainstorming..

https://cs.opensource.google/go/x/sys/+/dee7805f:windows/syscall_windows.go;l=1230

so we initialise WinSock2 and then call windows.WSARecvFrom

**Comment by gedw99** [comment]
Found the error codes too: 

https://learn.microsoft.com/en-us/windows/win32/winsock/windows-sockets-error-codes-2?redirectedfrom=MSDN

which will be helpful for side conditions

**Comment by achille-roussel** [comment]
Hello @gedw99 

The main reason Windows is not supported is our experience maintaining Windows compatibility in Wazero itself; WASI was tailored towards looking like a Unix API; it is a huge amount of work to succeed at making it work on Windows, where the system behavior and APIs are very different. Our current implementation is tested on Linux and Darwin, and we already had to handle system-specific conditions to achieve portability; supporting Windows will require a lot more of this.

We have a thorough test suite in wasi-go, so if you wanted to contribute a Windows compatibility layer, we would be happy to host the code, but we don't have the resources at this time to invest in this type of work.

I hope the answer helps, let me know!

**Comment by gedw99** [comment]
@achille-roussel 

thank you for explaining it and I see your point now. 

Impersonating a unix fs on windows is a tough use case.

I wish I had time to work on this but don’t. 

I should close this . Who knows maybe in the future is becomes possible
