### ISSUE TITLE
Potential concurrent map read writes errors

### ISSUE THREAD

**Issue by Taction** [stealthrocket/wasi-go#87]
The map read write is not protected under lock and using a global instance, which is finally used in the host function. https://github.com/stealthrocket/wasi-go/blob/main/imports/wasi_http/types/request.go#L40

If there are several wasm instances, there would be potential concurrent map writes errors.

**Comment by brendandburns** [comment]
cc @achille-roussel 

Is wasi-go intended to be used with multiple active WASM runtimes running in the same process?

The wasi-http code is definitely written in a way where it expects to only be instantiated a single time.

It's probably worth clarifying and either making the code concurrency safe, or throwing an error if it is instantiated multiple times.

**Comment by achille-roussel** [comment]
The `wasi.System` interface and its implementations are expected to be accessed by a single goroutine at a time; typically in wazero there's one goroutine executing a WASM module instance, and we expect that one instance of wasi-go would be associated with each guest module instance 👍

**Comment by Taction** [comment]
Thanks for the reply. I've added a test case in @brendandburns pr for adding wasi-http to Dapr binding to provide more context on how this could happen. I'm not sure if it is related to this repo or how the wasm instance is instantiated, but I think the test case could help to find where the issue actually is.

**Comment by brendandburns** [comment]
I will fix this based on this discussion above.

**Comment by Taction** [comment]
Hi, @brendandburns thanks for your fix! I also added some fixes based on your work.
